### PR TITLE
Switch to shelljs.

### PR DESCRIPTION
**Pull request by XhmikosR**
WIP; I need to sort a few stuff first and I'll CC you.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@pierreinglebert: I can't get istanbul to play nice. Any ideas?

**Comment by pierreinglebert** [comment]
For me the issue is at line [39](https://github.com/pierreinglebert/node-zopfli/pull/33/files#diff-da55c948ab565ebe30a2027fe5b721abR39)

You are putting file contents as arguments but coveralls is reading its stdin, shelljs doesnt seem to support pipe so I have no solution atm.

**Comment by XhmikosR** [comment]
Simple instabul  fails for me in Windows so I can't get so far in order to
try to fix it :/

**Comment by pierreinglebert** [comment]
For coveralls, the only solution I have is to replace coveralls with https://www.npmjs.com/package/istanbul-coveralls as shelljs doesn't support process.stdin.on('data').

What's your error ?

**Comment by XhmikosR** [comment]
@pierreinglebert:

```
C:\Users\xmr\Desktop\node-zopfli>node -v && npm -v
v0.12.2
2.7.4

C:\Users\xmr\Desktop\node-zopfli>node make test


  Zopfli buffer async
    √ should return a promise if no callback is given
    deflate
      √ should deflate using buffer by zopfli and inflated by node zlib
    zlib
      √ should zlib using buffer by node zlib
    gzip
      √ should gzip using buffer by node zlib

  Zopfli buffer sync
    deflate
      √ should deflate synchronously using buffer by node zlib
    zlib
      √ should zlib synchronously using buffer by node zlib
    gzip
      √ should deflate synchronously using buffer by node zlib

  Zopfli stream
    deflate
      √ should deflate using stream by node zlib (1375ms)
    zlib
      √ should inflate using stream by node zlib (1391ms)
    gzip
      √ should inflate using stream by node gzip (1406ms)


  10 passing (4s)


C:\Users\xmr\Desktop\node-zopfli>node make test-cov
No coverage information was collected, exit without writing coverage information

C:\Users\xmr\Desktop\node-zopfli\node_modules\.bin\_mocha:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\xmr\Desktop\node-zopfli\node_modules\istanbul\lib\hook.js:107:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (C:\Users\xmr\Desktop\node-zopfli\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    at C:\Users\xmr\Desktop\node-zopfli\node_modules\istanbul\lib\command\common\run-with-cover.js:248:17
    at C:\Users\xmr\Desktop\node-zopfli\node_modules\istanbul\lib\util\file-matcher.js:68:16
```

**Comment by XhmikosR** [comment]
Seems like a PATH issue with istanbul. I'll see if I can find a fix.

In the meantime, feel free to check out this branch and play with it if you want :)

**Comment by XhmikosR** [comment]
Was easier than I expected; I fixed `node make test-cov`. Now only `node make test-coveralls` fails.

**Comment by XhmikosR** [comment]
@pierreinglebert: can you check if coveralls is working right in the last patch? (don't merge even if it is, I want to squash the patches if that's the case)

**Comment by XhmikosR** [comment]
I added a patch with istanbul-coveralls too. Waiting for your feedback.

**Comment by XhmikosR** [comment]
Now that I'm thinking about it, we could just go with npm scripts unless you plan to add more stuff later.

**Comment by pierreinglebert** [comment]
Yes, that's a great idea ! It would be much more simpler to maintain & use.
For coveralls, it doesn't even need to run on windows as only travisci use it.

**Comment by XhmikosR** [comment]
OK cool. I'll make a new branch and then close this one.

BTW if that's the case,  we could even get rid of the development
dependency and just add it to Travis script.

**Comment by pierreinglebert** [comment]
If you do it, make the coveralls command without istanbul, I will use it in after_sucess in travis

**Comment by XhmikosR** [comment]
See #37.

**Pull request closed without merging**
