### PR TITLE
Add Appveyor badge.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by pierreinglebert** [comment]
Not sure that I want it :p
It does strange things such 2 builds for each commit or building tags when I set in the interface that he shouldn't.

**Comment by XhmikosR** [comment]
That is definitely something unrelated to the badge...

**Comment by XhmikosR** [comment]
For your issue: It's the way Appveyor works. You can choose to not build tags.

**Comment by pierreinglebert** [comment]
There is also the allow_failures that report failed build... I wrapped my head around that yesterday without success.
The badge will report a failed build even if it's okay, that's why I said that before.

**Comment by XhmikosR** [comment]
Well, it depends on what badge you use. The one I used is for the master branch build only.

Anyway, this cannot cause none of what you said above :P

**Comment by XhmikosR** [comment]
@pierreinglebert: I confirmed it's an issue with either io.js version AppVeyor is using or nan; it's unrelated to the badge like I told you, so you can merge this.

I have asked @FeodorFitsner for more info why `allow_failures` doesn't work in this case.

**Comment by FeodorFitsner** [comment]
Sorry guys for the delay with reply. Regarding `allow_failures`. Looking at [these lines](https://github.com/pierreinglebert/node-zopfli/blob/master/appveyor.yml#L17-L21). As I understand your intention is to allow io.js tests fail (btw, use `nodejs_version: ''` to grab the latest 2.0.1), but the problem is that platform is not defined as environment variable. It should be:

```
  allow_failures:
  - nodejs_version: ''
```

**Pull request merged**
