### PR TITLE
Improve help message for iterations.

### LINKED ISSUE #41: Improve help message
Regarding iterations etc.

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #41.

PS. I assume `ko` is a French thing :P

### CODE REVIEW

**Comment by pierreinglebert** [comment]
It's more commonly used in french because we like to be precise :D
There is a good explanation of the difference between octet and byte here : http://en.wikipedia.org/wiki/Octet_(computing)

**Comment by pierreinglebert** [comment]
I don't really mind about o or B. Can you just use the right prefixes -> KiB ?

**Comment by XhmikosR** [comment]
Update to use `KiB`. I'm not familiar with that personally, though.

**Comment by pierreinglebert** [comment]
You should use linux, it's everywhere there ^^

**Pull request merged**
